<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CProvML" nsURI="CProvML" nsPrefix="CProvML">
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceConnections" upperBound="-2"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetConnections" upperBound="-2"
        eType="#//Connection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CPU" eType="#//CPUType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OS" eType="#//OSType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RAM" lowerBound="1" upperBound="16"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Storage" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size" lowerBound="3" upperBound="2000"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//StorageType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodesDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" unique="false"
        lowerBound="1" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityGroup" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IPRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VPCName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//NetworkType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Environment" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EEnum" name="OSType">
    <eLiterals name="Windows"/>
    <eLiterals name="Linux"/>
    <eLiterals name="OSX"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CPUType">
    <eLiterals name="Intel"/>
    <eLiterals name="AMD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StorageType">
    <eLiterals name="SSD"/>
    <eLiterals name="HDD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NetworkType">
    <eLiterals name="HostOnly"/>
    <eLiterals name="Bridge"/>
    <eLiterals name="NAT"/>
  </eClassifiers>
</ecore:EPackage>
